create table public.clientes (
  id bigint generated by default as identity not null,
  nombre text null,
  apellido text null,
  cedula bigint null,
  telefono bigint null,
  "fechaHoraCita" timestamp with time zone null,
  estado text null default 'pendiente'::text,
  constraint clientes_pkey primary key (id)
) TABLESPACE pg_default;